project:
  type: website
  output-dir: _site
  title: "Starsim Style Guide"

website:
  title: "Starsim Style Guide"
  image: /assets/starsim-logo.png
  favicon: /assets/favicon.ico

  repo-url: https://github.com/starsimhub/styleguide
  repo-actions: [issue]
  page-navigation: true
  search:
    type: overlay

  page-footer:
    center: "© 2026 Starsim Development Team / Gates Foundation. All rights reserved. [Privacy and Cookies Notice](https://www.gatesfoundation.org/Privacy-and-Cookies-Notice) | [Terms of Use](https://www.gatesfoundation.org/Terms-of-Use)"
    right:
      - icon: github
        href: https://github.com/starsimhub/styleguide
        aria-label: GitHub
      - icon: envelope-at-fill
        href: mailto:info@starsim.org
      - icon: globe
        href: https://starsim.org/

  navbar:
    logo: /assets/starsim-logo.png
    title: "Starsim Style Guide"
    collapse-below: xxl
    tools:
      - icon: github
        href: https://github.com/starsimhub/styleguide
      - icon: envelope-at-fill
        href: mailto:info@starsim.org
      - icon: globe
        href: https://starsim.org

  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: 1_philosophy.md
        text: Philosophy
      - href: 2_python.md
        text: Python
      - href: 3_tests.md
        text: Tests
      - href: 4_documentation.md
        text: Documentation
      - href: 5_other.md
        text: Other
      - href: 6_zen.md
        text: Zen
      - href: engineering_quality_guidelines.md
        text: Engineering

format:
  html:
    theme:
      light: [cosmo, ./assets/styles-light.scss]
      dark: [cosmo, ./assets/styles-dark.scss]
    css: ./assets/styles.css
    toc: true
    toc-depth: 3
    highlight-style: github
